/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: All-Wide (https://sketchfab.com/dsm350)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/nissan-idx-nismo-258e8dca96404ab8b450c75cd110b5b6
title: Nissan IDX Nismo
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/carTest.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0.03, 0.01, -0.06]} rotation={[Math.PI / 2, 0, 0]} scale={0.6}>
            <mesh geometry={nodes.Object_4.geometry} material={materials.Chocofur_Free_Car_02_Exterior_01} />
          </group>
          <group position={[0.03, 0.01, -0.06]} rotation={[Math.PI / 2, 0, 0]} scale={0.6}>
            <mesh geometry={nodes.Object_6.geometry} material={materials.Chocofur_Free_Car_02_Exterior_01} />
          </group>
          <group position={[0.03, 0.01, -0.06]} rotation={[Math.PI / 2, 0, 0]} scale={0.6}>
            <mesh geometry={nodes.Object_8.geometry} material={materials.Chocofur_Free_Car_02_Exterior_01} />
          </group>
          <group position={[0.03, 0.01, -0.06]} rotation={[Math.PI / 2, 0, 0]} scale={0.6}>
            <mesh geometry={nodes.Object_10.geometry} material={materials.NISSAN_IDx_nismo_2014_body_n} />
          </group>
          <group position={[0.03, 0.01, -0.06]} rotation={[Math.PI / 2, 0, 0]} scale={0.6}>
            <mesh geometry={nodes.Object_12.geometry} material={materials.NISSAN_IDx_nismo_2014_body_n} />
          </group>
          <group position={[0.03, 0.01, -0.06]} rotation={[Math.PI / 2, 0, 0]} scale={0.6}>
            <mesh geometry={nodes.Object_14.geometry} material={materials.Chocofur_Free_Car_02_Exterior_01} />
          </group>
          <group position={[0.03, 0.01, -0.06]} rotation={[Math.PI / 2, 0, 0]} scale={0.6}>
            <mesh geometry={nodes.Object_16.geometry} material={materials.Chocofur_Free_Car_02_Exterior_01} />
          </group>
          <group position={[0.03, 0.01, -0.06]} rotation={[Math.PI / 2, 0, 0]} scale={0.6}>
            <mesh geometry={nodes.Object_18.geometry} material={materials.NISSAN_IDx_nismo_2014_body_n} />
          </group>
          <group position={[0.03, 0.01, -0.06]} rotation={[Math.PI / 2, 0, 0]} scale={0.6}>
            <mesh geometry={nodes.Object_20.geometry} material={materials.NISSAN_IDx_nismo_2014_body_n} />
          </group>
          <group position={[0.03, 0.01, -0.06]} rotation={[Math.PI / 2, 0, 0]} scale={0.6}>
            <mesh geometry={nodes.Object_22.geometry} material={materials.NISSAN_IDx_nismo_2014_body_n} />
          </group>
          <group position={[0.03, 0.01, -0.06]} rotation={[Math.PI / 2, 0, 0]} scale={0.6}>
            <mesh geometry={nodes.Object_24.geometry} material={materials['Material.001']} />
          </group>
          <group position={[0.03, 0.01, -0.06]} rotation={[Math.PI / 2, 0, 0]} scale={0.6}>
            <mesh geometry={nodes.Object_26.geometry} material={materials['Chocofur_Free_Car_02_Exterior_01.001']} />
          </group>
          <group position={[0.03, 0.01, -0.06]} rotation={[Math.PI / 2, 0, 0]} scale={0.6}>
            <mesh geometry={nodes.Object_28.geometry} material={materials['Chocofur_Free_Car_02_Exterior_01.001']} />
          </group>
          <group position={[0.03, 0.01, -0.06]} rotation={[Math.PI / 2, 0, 0]} scale={0.6}>
            <mesh geometry={nodes.Object_30.geometry} material={materials['Chocofur_Free_Car_02_Exterior_01.001']} />
          </group>
          <group position={[0.03, 0.01, -0.06]} rotation={[Math.PI / 2, 0, 0]} scale={0.6}>
            <mesh geometry={nodes.Object_32.geometry} material={materials.Chocofur_Free_Car_02_Glass_01} />
          </group>
          <group position={[0.03, 0.01, -0.06]} rotation={[Math.PI / 2, 0, 0]} scale={0.6}>
            <mesh geometry={nodes.Object_34.geometry} material={materials.NISSAN_IDx_nismo_2014_punch_n_add} />
          </group>
          <group position={[0.03, 0.01, -0.06]} rotation={[Math.PI / 2, 0, 0]} scale={0.6}>
            <mesh geometry={nodes.Object_36.geometry} material={materials.NISSAN_IDx_nismo_2014_punch_n_add} />
          </group>
          <group position={[0.03, 0.01, -0.06]} rotation={[Math.PI / 2, 0, 0]} scale={0.6}>
            <mesh geometry={nodes.Object_38.geometry} material={materials.NISSAN_IDx_nismo_2014_punch_n_add} />
          </group>
          <group position={[0.42, 0, -0.77]} rotation={[Math.PI / 2, 0.08, 0]} scale={[0.04, 0.03, 0.03]}>
            <mesh geometry={nodes.Object_40.geometry} material={materials['Circle.010Mat']} />
            <mesh geometry={nodes.Object_41.geometry} material={materials['Circle.007_Circle.006Mat']} />
            <mesh geometry={nodes.Object_42.geometry} material={materials['Circle.008Mat']} />
            <mesh geometry={nodes.Object_43.geometry} material={materials['Circle.005_Circle.009Mat']} />
          </group>
          <group position={[0.56, 0.01, -0.78]} rotation={[Math.PI / 2, 0.08, 0]} scale={[0.82, 0.58, 0.58]}>
            <mesh geometry={nodes.Object_45.geometry} material={materials['Material.020']} />
          </group>
          <group position={[0.48, 0, -0.77]} rotation={[-3.12, 0, -1.65]} scale={[0.18, 0.22, 0.18]}>
            <mesh geometry={nodes.Object_47.geometry} material={materials.stp_83_st60_1200pwide} />
          </group>
          <group position={[-0.38, -0.01, -0.77]} rotation={[-Math.PI / 2, 0.15, Math.PI]} scale={[0.04, 0.03, 0.03]}>
            <mesh geometry={nodes.Object_49.geometry} material={materials['Circle.010Mat']} />
            <mesh geometry={nodes.Object_50.geometry} material={materials['Circle.007_Circle.006Mat']} />
            <mesh geometry={nodes.Object_51.geometry} material={materials['Circle.008Mat']} />
            <mesh geometry={nodes.Object_52.geometry} material={materials['Circle.005_Circle.009Mat']} />
          </group>
          <group position={[-0.52, 0.01, -0.78]} rotation={[-Math.PI / 2, 0.15, -Math.PI]} scale={[0.82, 0.58, 0.58]}>
            <mesh geometry={nodes.Object_54.geometry} material={materials['Material.020']} />
          </group>
          <group position={[-0.44, 0, -0.77]} rotation={[3.12, 0, 1.72]} scale={[0.18, 0.22, 0.18]}>
            <mesh geometry={nodes.Object_56.geometry} material={materials.stp_83_st60_1200pwide} />
          </group>
          <group position={[-0.39, -0.01, 0.74]} rotation={[-Math.PI / 2, 0.06, -Math.PI]} scale={0.03}>
            <mesh geometry={nodes.Object_58.geometry} material={materials['Circle.010Mat']} />
            <mesh geometry={nodes.Object_59.geometry} material={materials['Circle.007_Circle.006Mat']} />
            <mesh geometry={nodes.Object_60.geometry} material={materials['Circle.008Mat']} />
            <mesh geometry={nodes.Object_61.geometry} material={materials['Circle.005_Circle.009Mat']} />
          </group>
          <group position={[-0.51, 0, 0.74]} rotation={[-Math.PI / 2, 0.06, -Math.PI]} scale={[0.72, 0.58, 0.58]}>
            <mesh geometry={nodes.Object_63.geometry} material={materials['Material.020']} />
          </group>
          <group position={[-0.43, 0, 0.75]} rotation={[3.12, 0, 1.63]} scale={[0.18, 0.19, 0.18]}>
            <mesh geometry={nodes.Object_65.geometry} material={materials.stp_83_st60_1200pwide} />
          </group>
          <group position={[0.44, 0, 0.74]} rotation={[Math.PI / 2, 0.06, 0]} scale={0.03}>
            <mesh geometry={nodes.Object_67.geometry} material={materials['Circle.010Mat']} />
            <mesh geometry={nodes.Object_68.geometry} material={materials['Circle.007_Circle.006Mat']} />
            <mesh geometry={nodes.Object_69.geometry} material={materials['Circle.008Mat']} />
            <mesh geometry={nodes.Object_70.geometry} material={materials['Circle.005_Circle.009Mat']} />
          </group>
          <group position={[0.56, 0, 0.74]} rotation={[Math.PI / 2, 0.06, 0]} scale={[0.72, 0.58, 0.58]}>
            <mesh geometry={nodes.Object_72.geometry} material={materials['Material.020']} />
          </group>
          <group position={[0.48, 0, 0.75]} rotation={[-3.12, 0, -1.63]} scale={[0.18, 0.19, 0.18]}>
            <mesh geometry={nodes.Object_74.geometry} material={materials.stp_83_st60_1200pwide} />
          </group>
          <group position={[0.18, 0.3, -1.27]} rotation={[1.43, 0, -1.56]} scale={[-0.05, 0.05, 0.05]}>
            <mesh geometry={nodes.Object_76.geometry} material={materials['Material.003']} />
          </group>
          <group position={[0.18, 0.3, -1.27]} rotation={[1.43, 0, -1.56]} scale={[-0.05, 0.05, 0.05]}>
            <mesh geometry={nodes.Object_78.geometry} material={materials['Material.002']} />
          </group>
          <group position={[0.18, 0.3, -1.27]} rotation={[1.43, 0, -1.56]} scale={[-0.05, 0.05, 0.05]}>
            <mesh geometry={nodes.Object_80.geometry} material={materials['Material.002']} />
          </group>
          <group position={[0.18, 0.3, -1.27]} rotation={[1.43, 0, -1.56]} scale={[-0.05, 0.05, 0.05]}>
            <mesh geometry={nodes.Object_82.geometry} material={materials['Material.002']} />
          </group>
          <group position={[0.03, 0.01, -0.06]} rotation={[Math.PI / 2, 0, 0]} scale={0.6}>
            <mesh geometry={nodes.Object_84.geometry} material={materials.NISSAN_IDx_nismo_2014_body_n} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/carTest.gltf')
